name: Run Python App

on:
  push:

jobs:
  run-app:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python app.py